export const imagesArray = [
         {
           link:
             "https://res.cloudinary.com/dpqyiwjbs/image/upload/v1564350738/ourchange/defaults/9.jpg"
         },
         {
           link:
             "https://res.cloudinary.com/dpqyiwjbs/image/upload/v1564350737/ourchange/defaults/5.jpg"
         },
         {
           link:
             "https://res.cloudinary.com/dpqyiwjbs/image/upload/v1564350737/ourchange/defaults/10.jpg"
         },
         {
           link:
             "https://res.cloudinary.com/dpqyiwjbs/image/upload/v1564350736/ourchange/defaults/8.jpg"
         },
         {
           link:
             "https://res.cloudinary.com/dpqyiwjbs/image/upload/v1564350734/ourchange/defaults/6.jpg"
         },
         {
           link:
             "https://res.cloudinary.com/dpqyiwjbs/image/upload/v1564350731/ourchange/defaults/7.jpg"
         },
         {
           link:
             "https://res.cloudinary.com/dpqyiwjbs/image/upload/v1564350985/ourchange/defaults/11.jpg"
         },
         {
           link:
             "https://res.cloudinary.com/dpqyiwjbs/image/upload/v1564350983/ourchange/defaults/12.jpg"
         },
         {
           link:
             "https://res.cloudinary.com/dpqyiwjbs/image/upload/v1564350982/ourchange/defaults/13.jpg"
         }
       ];

export const imagesArrayNews = [
  {
    link:
      "https://res.cloudinary.com/dpqyiwjbs/image/upload/v1564350729/ourchange/defaults/1.webp"
  },
  {
    link:
      "https://res.cloudinary.com/dpqyiwjbs/image/upload/v1564350743/ourchange/defaults/2.jpg"
  },
  {
    link:
      "https://res.cloudinary.com/dpqyiwjbs/image/upload/v1564350738/ourchange/defaults/3.jpg"
  },
  {
    link:
      "https://res.cloudinary.com/dpqyiwjbs/image/upload/v1564350733/ourchange/defaults/4.jpg"
  }
];
